### ISSUE TITLE
Support for IPStube possible?

### ISSUE THREAD

**Issue by ElToberino** [judge2005/EleksTubeIPS#22] opened 2024-11-21 16:40 UTC
Hello,
I wonder if this firmware could also support the "IPStube" clock, which is latterly available in many webshops at a really moderate price.
Searching the web I found some information about this device and there is a [pull requests in the EleksTubeHax](https://github.com/SmittyHalibut/EleksTubeHAX/pull/86) project to make this possible.

The main difference to the supported clocks seems to be the fact that there is only one single switch button - but I think this would be not a great problem, because in _your_ great software the settings are made via web interface.
The original firmware of the IPStube is controlled by a smartphone app which seems to have a lot of functions. This is nice, but - to be honest - running an unknown Chinese app and a web device without knowing what's going on under the hood ist not very advisable.

I don't know if it is a great thing to implement this device in your program - but I think it would be great for a lot of people because this device seems to be sold numerously.

**Comment by judge2005** [comment] 2024-11-24 15:26
Well that's a whole lot of changes and it isn't clear to me which are necessary and which are just code-cleanups that allow him to support new code that he added. I'll take a look but this would be an iterative process - someone will need to test the code to see what needs to be changed. It would be easier if someone who owns one of these clocks made the changes.

**Comment by judge2005** [comment] 2024-11-24 21:00
I've create a binary that should/might work. It incorporates the following modifications that I saw in the pull request:
- Uses the one button as the 'power' button
- Should use the correct pins to match the TFT controls
- Should work correctly with the IPS select hardware (i.e. it doesn't use a shift register)
- Should use the additional 4MB of flash for clock face and weather icon storage
What it doesn't currently do:
- It doesn't use the RTC chip. The Novellife SE uses the same chip and my code for that was not stable.
- It doesn't handle the underlighting available in the H402.
- It doesn't use the hardware display dimming support.
- Now that I'm typing this I recall that the dimming may have been inverted in this clock, or that may just have been if hardware dimming was being used.
Obviously there may be other things that don't work as expected, as I don't have any hardware to test this on.

**Comment by ElToberino** [comment] 2024-11-26 09:17
Great! Thanks a lot for your work!
I can't test it at the moment, because my device is still on it's way and hasn't arrived yet.
As soon as it does, I will flash your firmware, test everything and will report in here.

Thanks again that you spent your time for implemeting this. I look forward to trying everything out!

**Comment by TyberiusPrime** [comment] 2024-12-05 06:55
I'm getting 404 not found on bootloader.bin/partitions.bin/boot_app0.bin and firmware-ipstub-1.6.0.bin when trying to flash via that web page :(.

**Comment by TyberiusPrime** [comment] 2024-12-05 16:47
I tried `esptool.py --chip esp32 --port /dev/ttyUSB0 --baud 460800 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 40m --flash_size 8MB 0x1000 bootloader.bin 0x8000 partitions.bin 0xe000 boot_app0.bin 0x10000 firmware-ipstube-1.6.0.bin 0x180000 littlefs8MB-1.6.0.bin`

and now it's crashing on boot
```

1196ac

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x16 (SPI_FAST_FLASH_BOOT)
configsip: 153911750, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
E (36) esp_littlefs: failed to read addr 00307000, size 00000080, err 258
E (37) esp_littlefs: mount failed,  (-5)
E (37) esp_littlefs: Failed to initialize LittleFS
E (41) gpio: gpio_set_level(227): GPIO output gpio_num error
Guru Meditation Error: Core  1 panic'ed (Unhandled debug exception).
Debug exception reason: Stack canary watchpoint triggered (led task)
Core  1 register dump:
PC      : 0x40089445  PS      : 0x00060536  A0      : 0x801c1cd6  A1      : 0x3ffb45d0
A2      : 0x3ffb4bf8  A3      : 0x3ffb4814  A4      : 0x3ffb4854  A5      : 0x00000889
A6      : 0x3ffb6884  A7      : 0x00000001  A8      : 0x80084fb0  A9      : 0x00000002
A10     : 0x00000000  A11     : 0x00000000  A12     : 0x00000001  A13     : 0x3ffb6a30
A14     : 0x007b7c6c  A15     : 0x003fffff  SAR     : 0x00000004  EXCCAUSE: 0x00000001
EXCVADDR: 0x00000000  LBEG    : 0x4008b8bd  LEND    : 0x4008b8cd  LCOUNT  : 0xffffffff


Backtrace: 0x40089442:0x3ffb45d0 0x401c1cd3:0x3ffb4600 0x401b9a52:0x3ffb4620 0x401b9c0d:0x3ffb4930 0x401d5acd:0x3ffb4960 0x401366e2:0x3ffb4990 0x4013677f:0x3ffb49c0 0x40103f1a:0x3ffb4a40 0x40102532:0x3ffb4a60 0x400f7eed:0x3ffb4aa0 0x400d32ce:0x3ffb4ac0 0x400da31d:0x3ffb4b00
```

**Comment by judge2005** [comment] 2024-12-05 18:51
Try littlefs-1.6.0.bin. If that works I would be interested to see the info page in the GUI.

**Comment by judge2005** [comment] 2024-12-05 19:09
> I'm getting 404 not found on bootloader.bin/partitions.bin/boot_app0.bin and firmware-ipstub-1.6.0.bin when trying to flash via that web page :(.

Could you post a screenshot of the error you see?

**Comment by TyberiusPrime** [comment] 2024-12-06 07:01
Thank you for getting back to me, @judge2005 .
Here's the screenshot, should've added that right away.
![image](https://github.com/user-attachments/assets/89b31573-d514-48dc-8cbb-2291bfdaff4f)

usinge littlefs-1.6.0.bin get's me a different panic
```

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x16 (SPI_FAST_FLASH_BOOT)
configsip: 153911750, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
E (47) gpio: gpio_set_level(227): GPIO output gpio_num error
Guru Meditation Error: Core  1 panic'ed (Double exception).

Core  1 register dump:
PC      : 0x4008e2ee  PS      : 0x00040d36  A0      : 0x801b9a92  A1      : 0x3ffb4af0
A2      : 0x00000003  A3      : 0x00060d23  A4      : 0x00060d20  A5      : 0x3ffb4e40
A6      : 0x00000032  A7      : 0x3ffb4e40  A8      : 0x40080080  A9      : 0x3ffb4c10
A10     : 0x00060f36  A11     : 0x00040026  A12     : 0x3ffb4e64  A13     : 0x0000ff00
A14     : 0x00000004  A15     : 0xff000000  SAR     : 0x00000004  EXCCAUSE: 0x00000002
EXCVADDR: 0xffffffe0  LBEG    : 0x4008b8bd  LEND    : 0x4008b8cd  LCOUNT  : 0xfffffffe


Backtrace: 0x4008e2eb:0x3ffb4af0 0x401b9a8f:0x3ffb4b10 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b60 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4bb0 0x4008e2eb:0x3ffb4be0 0x4008e2eb:0x3ffb4c10 0x4008007d:0x3ffb4af0 0x4008f223:0x3ffb4b10 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b60 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4bb0 0x4008e2eb:0x3ffb4be0 0x4008e2eb:0x3ffb4c10 0x4008007d:0x3ffb4af0 0x4008f223:0x3ffb4b10 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b60 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4bb0 0x4008e2eb:0x3ffb4be0 0x4008e2eb:0x3ffb4c10 0x4008007d:0x3ffb4af0 0x4008f223:0x3ffb4b10 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b60 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4bb0 0x4008e2eb:0x3ffb4be0 0x4008e2eb:0x3ffb4c10 0x4008007d:0x3ffb4af0 0x4008f223:0x3ffb4b10 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b60 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4bb0 0x4008e2eb:0x3ffb4be0 0x4008e2eb:0x3ffb4c10 0x4008007d:0x3ffb4af0 0x4008f223:0x3ffb4b10 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b60 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4bb0 0x4008e2eb:0x3ffb4be0 0x4008e2eb:0x3ffb4c10 0x4008007d:0x3ffb4af0 0x4008f223:0x3ffb4b10 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b60 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4bb0 0x4008e2eb:0x3ffb4be0 0x4008e2eb:0x3ffb4c10 0x4008007d:0x3ffb4af0 0x4008f223:0x3ffb4b10 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b60 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4bb0 0x4008e2eb:0x3ffb4be0 0x4008e2eb:0x3ffb4c10 0x4008007d:0x3ffb4af0 0x4008f223:0x3ffb4b10 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b60 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4bb0 0x4008e2eb:0x3ffb4be0 0x4008e2eb:0x3ffb4c10 0x4008007d:0x3ffb4af0 0x4008f223:0x3ffb4b10 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b60 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4bb0 0x4008e2eb:0x3ffb4be0 0x4008e2eb:0x3ffb4c10 0x4008007d:0x3ffb4af0 0x4008f223:0x3ffb4b10 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b60 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4bb0 0x4008e2eb:0x3ffb4be0 0x4008e2eb:0x3ffb4c10 0x4008007d:0x3ffb4af0 0x4008f223:0x3ffb4b10 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b60 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4bb0 0x4008e2eb:0x3ffb4be0 0x4008e2eb:0x3ffb4c10 0x4008007d:0x3ffb4af0 0x4008f223:0x3ffb4b10 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b60 0x4008e2eb:0x3ffb4b80 |<-CONTINUES




ELF file SHA256: 9bf9002b391196ac

Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x4009110d  PS      : 0x00060034  A0      : 0x8013ca68  A1      : 0x3ffd7390
A2      : 0xa5a5a5ad  A3      : 0xa5a5a5a5  A4      : 0x3ffb4e64  A5      : 0x0000024c
A6      : 0x00000008  A7      : 0x3ffd756c  A8      : 0x8009116d  A9      : 0x3ffd7370
A10     : 0x3ffb4e6c  A11     : 0x3f416678  A12     : 0x000000ff  A13     : 0x0000ff00
A14     : 0x00ff0000  A15     : 0xff000000  SAR     : 0x00000018  EXCCAUSE: 0x0000001c
EXCVADDR: 0xa5a5a5b1  LBEG    : 0x4008b8bd  LEND    : 0x4008b8cd  LCOUNT  : 0xfffffffe


Backtrace: 0x4009110a:0x3ffd7390 0x4013ca65:0x3ffd73d0 0x4013d623:0x3ffd73f0 0x4013da5a:0x3ffd7480 0x4013ca07:0x3ffd74b0




ELF file SHA256: 9bf9002b391196ac

Re-entered core dump! Exception happened during core dump!
Rebooting...
```

**Comment by judge2005** [comment] 2024-12-06 12:58
Re. 404: Wordpress has some weird storage semantics. I can fix that, but that probably won’t fix the crashing.

Re. Your real problem, I’ll take a look. Seems like my memory map and/or pin assignments are wrong. Any info you can provide about the hardware there would be much appreciated (photos of ESP32 plus any pin assignments you can tease out). Do you have a link to where you bought your clock from?

**Comment by TyberiusPrime** [comment] 2024-12-06 13:25
I got it here, the sleek box was labeled H401.
https://de.aliexpress.com/item/1005006156895417.html?gatewayAdapt=glo2deu

I haven't been able to open it in my lunch time - it's got four screws on the bottom, but the bottoms's either a very tight fit or glued in.

**Comment by judge2005** [comment] 2024-12-07 01:52
> I'm getting 404 not found on bootloader.bin/partitions.bin/boot_app0.bin and firmware-ipstub-1.6.0.bin when trying to flash via that web page :(.

Try now (no bugs fixed, but it should at least find the files!

**Comment by RECase58** [comment] 2024-12-07 01:59
Firmware only works, but the full install fails in the same way as before.

**Comment by RECase58** [comment] 2024-12-07 02:06
![IPSTube H401_ESP32](https://github.com/user-attachments/assets/42859501-8b4b-448e-9d03-10f81fc391d3)
Here's the ESP32 photo.

**Comment by RECase58** [comment] 2024-12-07 02:25
Here are the support chips.
![IPSTube H401_ESP32_Support_chips](https://github.com/user-attachments/assets/4525e4b0-3c85-4736-be5a-fb847ff377c5)

**Comment by RECase58** [comment] 2024-12-07 02:26
Different lighting so the traces can be seen better.
Let me know if you need anything else.
![IPSTube H401_Traces](https://github.com/user-attachments/assets/4c849141-1871-4f48-9e55-8703d39890a4)

**Comment by judge2005** [comment] 2024-12-07 16:28
There were several things going on here. Hopefully I've fixed them all. Please try the [browser-based install](https://www.nixies.us/projects/elekstubeips-clock/elekstube-ips-v1-2-2/) again.

Note this still doesn't mean that the firmware will work, but it should at least install and not crash. I have ordered a clock from Ali Express and will try it out when it arrives.

Thanks for your patience.

**Comment by TyberiusPrime** [comment] 2024-12-08 17:47
I can confirm that it flashes via the browser now.

And no, I have to thank you!. Pickup up a clock just to get our open source firmware running on it is way beyond anything anybody could ever expect you to do!

**Comment by judge2005** [comment] 2024-12-08 18:12
It was so cheap, I couldn't resist. Like I need another clock lol.

So after flashing, can you access the GUI and/or what does the console show - you should be able to see it from the browser.

**Comment by TyberiusPrime** [comment] 2024-12-09 06:30
Flashing works, the fimware, not so much 
```
rst:0x3 (SW_RESET),boot:0x16 (SPI_FAST_FLASH_BOOT)
configsip: 153911750, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
ets Jul 29 2019 12:21:46
rst:0x3 (SW_RESET),boot:0x16 (SPI_FAST_FLASH_BOOT)
```

Is what I see on the console/esp-monitor now.
It crashes rapidly though :).

**Comment by TyberiusPrime** [comment] 2024-12-11 07:02
sorry for the delay, here's what the current web-flashed firmware has to say.

serial console:
```
ELF file SHA256: d13be71a353cc3b3

Re-entered core dump! Exception happened during core dump!
Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x16 (SPI_FAST_FLASH_BOOT)
configsip: 153911750, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
E (34) gpio: gpio_set_level(227): GPIO output gpio_num error
Guru Meditation Error: Core  1 panic'ed (Double exception).

Core  1 register dump:
PC      : 0x4008e2ee  PS      : 0x00040b36  A0      : 0x801b9c10  A1      : 0x3ffb4a90
A2      : 0x3ffbf7d8  A3      : 0xffffffff  A4      : 0x00060b20  A5      : 0x0000000c
A6      : 0x007b6a7c  A7      : 0x003fffff  A8      : 0x40080080  A9      : 0x3ffb4bd0
A10     : 0x00060d36  A11     : 0x00040026  A12     : 0x3f407a44  A13     : 0x3ffb4fd0
A14     : 0x3ffb4f80  A15     : 0x0000000c  SAR     : 0x0000001d  EXCCAUSE: 0x00000002
EXCVADDR: 0xffffffe0  LBEG    : 0x4008b8bd  LEND    : 0x4008b8cd  LCOUNT  : 0xffffffff


Backtrace: 0x4008e2eb:0x3ffb4a90 0x401b9c0d:0x3ffb4ad0 0x4008e2eb:0x3ffb4af0 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b50 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4ba0 0x4008e2eb:0x3ffb4bd0 0x4008007d:0x3ffb4a90 0x40090c38:0x3ffb4ad0 0x4008e2eb:0x3ffb4af0 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b50 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4ba0 0x4008e2eb:0x3ffb4bd0 0x4008007d:0x3ffb4a90 0x40090c38:0x3ffb4ad0 0x4008e2eb:0x3ffb4af0 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b50 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4ba0 0x4008e2eb:0x3ffb4bd0 0x4008007d:0x3ffb4a90 0x40090c38:0x3ffb4ad0 0x4008e2eb:0x3ffb4af0 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b50 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4ba0 0x4008e2eb:0x3ffb4bd0 0x4008007d:0x3ffb4a90 0x40090c38:0x3ffb4ad0 0x4008e2eb:0x3ffb4af0 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b50 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4ba0 0x4008e2eb:0x3ffb4bd0 0x4008007d:0x3ffb4a90 0x40090c38:0x3ffb4ad0 0x4008e2eb:0x3ffb4af0 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b50 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4ba0 0x4008e2eb:0x3ffb4bd0 0x4008007d:0x3ffb4a90 0x40090c38:0x3ffb4ad0 0x4008e2eb:0x3ffb4af0 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b50 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4ba0 0x4008e2eb:0x3ffb4bd0 0x4008007d:0x3ffb4a90 0x40090c38:0x3ffb4ad0 0x4008e2eb:0x3ffb4af0 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b50 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4ba0 0x4008e2eb:0x3ffb4bd0 0x4008007d:0x3ffb4a90 0x40090c38:0x3ffb4ad0 0x4008e2eb:0x3ffb4af0 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b50 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4ba0 0x4008e2eb:0x3ffb4bd0 0x4008007d:0x3ffb4a90 0x40090c38:0x3ffb4ad0 0x4008e2eb:0x3ffb4af0 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b50 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4ba0 0x4008e2eb:0x3ffb4bd0 0x4008007d:0x3ffb4a90 0x40090c38:0x3ffb4ad0 0x4008e2eb:0x3ffb4af0 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b50 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4ba0 0x4008e2eb:0x3ffb4bd0 0x4008007d:0x3ffb4a90 0x40090c38:0x3ffb4ad0 0x4008e2eb:0x3ffb4af0 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b50 0x4008e2eb:0x3ffb4b80 0x4008e2eb:0x3ffb4ba0 0x4008e2eb:0x3ffb4bd0 0x4008007d:0x3ffb4a90 0x40090c38:0x3ffb4ad0 0x4008e2eb:0x3ffb4af0 0x4008e2eb:0x3ffb4b30 0x4008e2eb:0x3ffb4b50 |<-CONTINUES




ELF file SHA256: d13be71a353cc3b3

Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x4009110d  PS      : 0x00060034  A0      : 0x8013ca68  A1      : 0x3ffd7390
A2      : 0x0000000b  A3      : 0x003fffff  A4      : 0x3ffb4fd0  A5      : 0x0000024c
A6      : 0x00000008  A7      : 0x3ffd756c  A8      : 0x8009116d  A9      : 0x3ffd7370
A10     : 0x3ffb4fd8  A11     : 0x3f416678  A12     : 0x000000ff  A13     : 0x0000ff00
A14     : 0x00ff0000  A15     : 0xff000000  SAR     : 0x0000001a  EXCCAUSE: 0x0000001c
EXCVADDR: 0x0040000b  LBEG    : 0x4008b8bd  LEND    : 0x4008b8cd  LCOUNT  : 0xfffffffe


Backtrace: 0x4009110a:0x3ffd7390 0x4013ca65:0x3ffd73d0 0x4013d623:0x3ffd73f0 0x4013da5a:0x3ffd7480 0x4013ca07:0x3ffd74b0


```

and accordingly no gui.

**Comment by judge2005** [comment] 2024-12-11 18:14
Try one more time. After this I'll wait until my hardware arrives in about a week.

**Comment by RECase58** [comment] 2024-12-13 01:32
It looks like 1.6.2 installs properly and does not generate any errors.  The web interface is presented on the created AP.  WiFi will connect to an AP.  The LEDs all work as expected.  The displays do not seem to initialize and remain dark.  It does not seem to be a backlighting issue as no image is seen when external lighting is applied to the side of the display.  I have not yet checked to see if the MQTT is working.  Progress!  Thanks again for all the efforts!

**Comment by judge2005** [comment] 2024-12-13 20:35
I found a bug related to enabling displays for the IPSTube clocks. I've uploaded a fix to the web site. Please try again(!) - note the version number is the same.

**Comment by RECase58** [comment] 2024-12-14 01:33
No joy on the displays being enabled.  From the nixies.us web page, I tried just the firmware update and then the full install.  

Then I tried uploading the binaries with esptool using this:
esptool --chip esp32 --port COM3 --baud 230400 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 40m --flash_size 8MB 0x1000 bootloader8MB.bin 0x8000 partitions8MB.bin 0xe000 boot_app0.bin 0x10000 firmware-ipstube-1.6.2.bin 0x180000 littlefs8MB-1.6.2.bin

Thanks for trying.  I guess we'll just have to wait until you have actual hardware in your hands.

**Comment by RECase58** [comment] 2024-12-14 01:38
Just FYI, the IPSTube original firmwares do not seem to be locked to the MAC address of the board.  I have 2 clocks and their backups can be loaded interchangeably.

**Comment by judge2005** [comment] 2024-12-14 17:16
I received my hardware today and I've uploaded new version to https://www.nixies.us/projects/elekstubeips-clock/elekstube-ips-v1-2-2/. I noticed that I have to put my clock in boot mode and that I can't configure the WiFi directly from the web page - I've updated the instructions accordingly.

**Comment by RECase58** [comment] 2024-12-15 01:23
Version 1.6.3 works.  Congratulations! I have cycled through all of the various options and all seem to be working as designed.

**Comment by judge2005** [comment] 2024-12-15 04:39
I'm thinking of changing the one button to cycle through the modes - time -> date -> weather forecast and back.

**Comment by RECase58** [comment] 2024-12-15 05:36
And now the flood of enhancements begins...  ;) 

The button cycling through the views sounds good.
I love being able to update settings via the web page.  Any chance of making them available for setting via MQTT?
A slider for clock brightness would be nice so the clock is not overwhelming in a dark room. If the MQTT settings are implemented, then HomeAssistant could regulate brightness based on ambient light levels.

Again, thanks for a great project.  I wish I had more skills so I could help implement such enhancements, but I am a newcomer to small systems.

**Comment by TyberiusPrime** [comment] 2024-12-15 08:35
Came back this morning to a frozen screensaver. Triggering the button didn't work. After power reset, it did have the right time, so idk.

Would love more mqtt commands to swap clockfaces / show arbitrary images :).

**Comment by judge2005** [comment] 2024-12-15 12:05
> Came back this morning to a frozen screensaver. Triggering the button didn't work. After power reset, it did have the right time, so idk.
> 
> 
> 

I noticed this one too. Can you create a separate issue for it?

**Comment by judge2005** [comment] 2024-12-15 12:12
> And now the flood of enhancements begins...  ;) 
> 
> 
> 
> The button cycling through the views sounds good.
> 
> I love being able to update settings via the web page.  Any chance of making them available for setting via MQTT?
> 
> A slider for clock brightness would be nice so the clock is not overwhelming in a dark room. If the MQTT settings are implemented, then HomeAssistant could regulate brightness based on ambient light levels.
> 
> 

You can do this with MQTT/homeassistant. See https://github.com/judge2005/EleksTubeIPS/wiki/User-Guide#mqtthome-assistant

> 
> Again, thanks for a great project.  I wish I had more skills so I could help implement such enhancements, but I am a newcomer to small systems.

**Comment by judge2005** [comment] 2024-12-15 12:18
I'm going to close this issue. Please create separate issues for any bugs you find and create discussions for new feature requests, questions or observations.

**Closed** 2024-12-15 12:19 UTC

**Comment by judge2005** [comment] 2024-12-15 19:12
Just to finish up this thread - I've created v1.6.4 that fixes some pre-existing bugs. See [the release notes](https://github.com/judge2005/EleksTubeIPS/releases/tag/v1.6.4) for details.
